### ISSUE TITLE
Where is the script to draw the trajectory into the Google Maps

### ISSUE THREAD

**Issue by Osborn28** [Robotics-BUT/Brno-Urban-Dataset-Tools#1]
Hi, thanks for your team's contribution to this dataset.
In the paper, "_We also provide a set of several Python-OpenCV based scripts that helps to process the video data into separated frame files, or the drawing the trajectory into the Google Maps, etc._"
But I can't find the script that helps to draw the trajectory into the Google Maps. Are there any plans to open source this script?

**Comment by adamek727** [comment]
Thanks for notice. I have updated master branch with simple map-plotting example. 
In one week or so there should be a tool for LiDAR to camera projection.

**Comment by adamek727** [comment]
Also please notice, that the map plotting example is using the gmplot python library for which you need to have a valid Google API.
