### ISSUE TITLE
ImportError: No module named custom_msgs.msg

### ISSUE THREAD

**Issue by bryantaoli** [Robotics-BUT/Brno-Urban-Dataset-Tools#2]
Hi, thanks for your team's contribution to this dataset.
After I ran the code main.py in the /bag_builder the ptthon gave me a mistake as:
![image](https://user-images.githubusercontent.com/30526360/76747103-941da880-67b3-11ea-85e2-eb65da3e6bd0.png)
Can you tell me how to fix the bug?

**Comment by RoboticsBUT** [comment]
Working on it. We have here some infrastructure complications and I am currently not able to access source codes on git. There is a problem, that you do not have created custom message that is defined in ROS workspace that we are using for the recording purposes. I will fix it as fast as possible.

**Comment by bryantaoli** [comment]
Thank you, and maybe some CmakeLists you have forgot to upload in the repository.

**Comment by RoboticsBUT** [comment]
Hi, I have added custom message definitions into the repository. Please feel free to use them. If you would have any question, please let me know.
